# Generated by Django 2.2.16 on 2022-03-03 15:23

import common.models.base
import common.models.json
from django.db import migrations, models
import src.manager.module_intent.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='创建人')),
                ('created_at', common.models.base.FormatDateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='更新人')),
                ('updated_at', common.models.base.FormatDateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='删除人')),
                ('deleted_at', common.models.base.FormatDateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('biz_id', models.PositiveIntegerField(db_index=True, default=0, verbose_name='业务ID')),
                ('biz_name', models.CharField(default='', max_length=128, verbose_name='业务名称')),
                ('bot_id', models.CharField(default='', max_length=128, verbose_name='机器人ID')),
                ('bot_name', models.CharField(default='', max_length=128, verbose_name='机器人名称')),
                ('bot_type', models.CharField(choices=[('xwork', '企业微信'), ('qq', 'QQ'), ('wechat', '微信'), ('slack', 'SLACK'), ('default', 'OPSBOT')], default='default', max_length=128, verbose_name='机器人类型')),
                ('config', src.manager.module_intent.models.CompressJSONField(default={}, verbose_name='机器人配置')),
            ],
            options={
                'verbose_name': '【机器人】',
                'verbose_name_plural': '【机器人】',
                'db_table': 'tab_bot',
            },
        ),
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='创建人')),
                ('created_at', common.models.base.FormatDateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='更新人')),
                ('updated_at', common.models.base.FormatDateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='删除人')),
                ('deleted_at', common.models.base.FormatDateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('biz_id', models.PositiveIntegerField(db_index=True, default=0, verbose_name='业务ID')),
                ('intent_id', models.BigIntegerField(default=-1, verbose_name='意图ID')),
                ('intent_name', models.CharField(default='', max_length=128, verbose_name='技能名称')),
                ('intent_create_user', models.CharField(default='', max_length=128, verbose_name='意图添加人')),
                ('bot_name', models.CharField(default='', max_length=128, verbose_name='机器人名称')),
                ('bot_type', models.CharField(default='default', max_length=128, verbose_name='机器人类型')),
                ('platform', models.IntegerField(choices=[(0, 'DEFAULT'), (1, 'JOB'), (2, 'SOPS'), (3, 'DEV_OPS'), (4, 'DEFINE')], default=0, verbose_name='平台类型')),
                ('project_id', models.CharField(default='', max_length=128, verbose_name='项目ID')),
                ('feature_id', models.CharField(default='', max_length=128, verbose_name='特色ID:蓝盾-流水线ID')),
                ('task_id', models.CharField(default='', max_length=128, verbose_name='任务ID')),
                ('sender', models.CharField(default='', max_length=128, verbose_name='执行人')),
                ('rtx', models.CharField(default='', max_length=128, verbose_name='rtx接受人')),
                ('msg', models.TextField(default='', verbose_name='调用信息')),
                ('status', models.IntegerField(choices=[(0, 'INIT'), (1, 'RUNNING'), (2, 'SUCCESS'), (3, 'FAIL'), (4, 'SUSPENDED'), (5, 'REMOVE')], default=0, verbose_name='任务状态')),
                ('params', common.models.json.DictCharField(default=[], verbose_name='执行参数')),
            ],
            options={
                'verbose_name': '【任务日志】',
                'verbose_name_plural': '【任务日志】',
                'db_table': 'tab_intent_execution_log',
            },
        ),
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='创建人')),
                ('created_at', common.models.base.FormatDateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='更新人')),
                ('updated_at', common.models.base.FormatDateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='删除人')),
                ('deleted_at', common.models.base.FormatDateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('index_id', models.BigIntegerField(default=-1, verbose_name='索引ID')),
                ('biz_id', models.PositiveIntegerField(db_index=True, default=0, verbose_name='业务ID')),
                ('intent_name', models.CharField(default='', max_length=128, verbose_name='技能名称')),
                ('status', models.BooleanField(default=True, verbose_name='意图状态')),
                ('available_user', src.manager.module_intent.models.CompressJSONField(default=[], verbose_name='可执行用户')),
                ('available_group', src.manager.module_intent.models.CompressJSONField(default=[], verbose_name='可执行群组')),
                ('is_commit', models.BooleanField(default=True, verbose_name='执行确认')),
                ('serial_number', models.CharField(default='-1', max_length=128, verbose_name='序列号')),
                ('developer', common.models.json.DictCharField(default=[], verbose_name='开发商')),
                ('approver', common.models.json.DictCharField(default=[], verbose_name='审批人')),
            ],
            options={
                'verbose_name': '【意图】',
                'verbose_name_plural': '【意图】',
                'db_table': 'tab_intent',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='创建人')),
                ('created_at', common.models.base.FormatDateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='更新人')),
                ('updated_at', common.models.base.FormatDateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='删除人')),
                ('deleted_at', common.models.base.FormatDateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('biz_id', models.PositiveIntegerField(db_index=True, default=0, verbose_name='业务ID')),
                ('index_id', models.BigIntegerField(default=-1, verbose_name='索引ID')),
                ('platform', models.CharField(choices=[('JOB', 'JOB'), ('SOPS', '标准运维'), ('DEVOPS', '蓝盾'), ('DEFINE', '自定义')], default='JOB', max_length=128, verbose_name='平台名称')),
                ('task_id', models.CharField(default='', max_length=128, verbose_name='任务ID')),
                ('project_id', models.CharField(default='', max_length=128, verbose_name='项目id')),
                ('activities', src.manager.module_intent.models.CompressJSONField(default=[], verbose_name='节点信息')),
                ('slots', src.manager.module_intent.models.CompressJSONField(default=[], verbose_name='槽位信息')),
                ('source', src.manager.module_intent.models.CompressJSONField(default={}, verbose_name='任务元数据')),
                ('script', models.TextField(default='', verbose_name='执行脚本信息')),
            ],
            options={
                'verbose_name': '【任务信息】',
                'verbose_name_plural': '【任务信息】',
                'db_table': 'tab_intent_task',
            },
        ),
        migrations.CreateModel(
            name='Utterances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='创建人')),
                ('created_at', common.models.base.FormatDateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='更新人')),
                ('updated_at', common.models.base.FormatDateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='删除人')),
                ('deleted_at', common.models.base.FormatDateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('biz_id', models.PositiveIntegerField(db_index=True, default=0, verbose_name='业务ID')),
                ('index_id', models.BigIntegerField(default=-1, verbose_name='索引ID')),
                ('content', src.manager.module_intent.models.CompressJSONField(default=[], verbose_name='语料列表')),
            ],
            options={
                'verbose_name': '【语料库】',
                'verbose_name_plural': '【语料库】',
                'db_table': 'tab_intent_utterances',
            },
        ),
    ]
