# Generated by Django 2.2.16 on 2022-07-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_intent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intent',
            name='notice_discern_success',
            field=models.BooleanField(default=True, verbose_name='识别成功通知'),
        ),
        migrations.AddField(
            model_name='intent',
            name='notice_exec_success',
            field=models.BooleanField(default=True, verbose_name='启动成功通知'),
        ),
        migrations.AddField(
            model_name='intent',
            name='notice_single',
            field=models.BooleanField(default=False, verbose_name='通知个人'),
        ),
        migrations.AddField(
            model_name='intent',
            name='notice_start_success',
            field=models.BooleanField(default=True, verbose_name='启动成功通知'),
        ),
    ]
