# Generated by Django 2.2.6 on 2020-10-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module_intent", "0002_auto_20201009_1142"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intent",
            name="status",
            field=models.BooleanField(default=True, verbose_name="意图状态"),
        ),
    ]
