# Generated by Django 2.2.16 on 2022-07-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_intent', '0002_auto_20220718_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionlog',
            name='notice_exec_success',
            field=models.BooleanField(default=True, verbose_name='执行成功是否通知'),
        ),
    ]
