# Generated by Django 2.2.16 on 2022-10-31 17:11

import common.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_intent', '0004_executionlog_task_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='创建人')),
                ('created_at', common.models.base.FormatDateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='更新人')),
                ('updated_at', common.models.base.FormatDateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='删除人')),
                ('deleted_at', common.models.base.FormatDateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('biz_id', models.PositiveIntegerField(db_index=True, default=0, verbose_name='业务ID')),
                ('tag_name', models.CharField(max_length=128, verbose_name='标签名称')),
                ('tag_index', models.IntegerField(verbose_name='标签索引')),
            ],
            options={
                'verbose_name': '【技能标签】',
                'verbose_name_plural': '【技能标签】',
                'db_table': 'tab_intent_tag',
                'ordering': ('tag_index',),
            },
        ),
    ]
