# Generated by Django 2.2.6 on 2020-12-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module_intent", "0004_auto_20201014_1411"),
    ]

    operations = [
        migrations.AddField(
            model_name="intent",
            name="is_commit",
            field=models.BooleanField(default=True, verbose_name="执行确认"),
        ),
    ]
