# Generated by Django 2.2.6 on 2020-12-28 17:01

from django.db import migrations
import module_intent.models


class Migration(migrations.Migration):

    dependencies = [
        ("module_intent", "0005_intent_is_commit"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="activities",
            field=module_intent.models.CompressJSONField(
                default=[], verbose_name="节点信息"
            ),
        ),
    ]
