# Generated by Django 2.2.16 on 2023-11-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_intent', '0006_intent_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='intent',
            name='match_pattern',
            field=models.IntegerField(default=1, verbose_name='技能匹配模式'),
        ),
    ]
