# Generated by Django 2.2.16 on 2025-12-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_intent', '0007_intent_match_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='intent',
            name='service_catalogue',
            field=models.CharField(default='', max_length=128, verbose_name='服务目录'),
        ),
        migrations.AlterField(
            model_name='executionlog',
            name='platform',
            field=models.IntegerField(choices=[(0, 'DEFAULT'), (1, 'JOB'), (2, 'SOPS'), (3, 'DEV_OPS'), (4, 'DEFINE'), (5, 'ITSM')], default=0, verbose_name='平台类型'),
        ),
        migrations.AlterField(
            model_name='task',
            name='platform',
            field=models.CharField(choices=[('JOB', 'JOB'), ('SOPS', '标准运维'), ('DEVOPS', '蓝盾'), ('DEFINE', '自定义'), ('ITSM', 'ITSM'), ('MONITOR_DASHBOARD', '监控仪表盘')], default='JOB', max_length=128, verbose_name='平台名称'),
        ),
    ]
