# Generated by Django 2.2.6 on 2021-07-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_intent', '0008_auto_20210705_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionlog',
            name='platform',
            field=models.IntegerField(choices=[(1, 'JOB'), (2, 'SOPS'), (3, 'DEV_OPS'), (4, 'DEFINE')], default=0, verbose_name='平台类型'),
        ),
        migrations.AlterField(
            model_name='executionlog',
            name='status',
            field=models.IntegerField(choices=[(0, 'INIT'), (1, 'RUNNING'), (2, 'SUCCESS'), (3, 'FAIL'), (4, 'SUSPENDED'), (5, 'REMOVE')], default='0', max_length=128, verbose_name='任务状态'),
        ),
    ]
