# Generated by Django 2.2.6 on 2021-07-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_intent', '0010_auto_20210706_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionlog',
            name='intent_create_user',
            field=models.CharField(default='', max_length=128, verbose_name='意图添加人'),
        ),
    ]
