# Generated by Django 2.2.6 on 2021-07-12 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_intent', '0008_auto_20210709_1911'),
        ('module_intent', '0011_executionlog_intent_create_user'),
    ]

    operations = [
    ]
