# Generated by Django 2.2.6 on 2021-09-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module_intent", "0015_auto_20210715_2057"),
    ]

    operations = [
        migrations.AddField(
            model_name="executionlog",
            name="rtx",
            field=models.CharField(default="", max_length=128, verbose_name="rtx接受人"),
        ),
    ]
