# Generated by Django 2.2.6 on 2021-11-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module_intent", "0017_auto_20211105_1712"),
    ]

    operations = [
        migrations.AddField(
            model_name="intent",
            name="developer",
            field=models.CharField(default="", max_length=128, verbose_name="开发商"),
        ),
        migrations.AlterField(
            model_name="bot",
            name="created_by",
            field=models.CharField(blank=True, default="admin", max_length=255, null=True, verbose_name="创建人"),
        ),
        migrations.AlterField(
            model_name="bot",
            name="deleted_by",
            field=models.CharField(blank=True, default="admin", max_length=255, null=True, verbose_name="删除人"),
        ),
        migrations.AlterField(
            model_name="bot",
            name="updated_by",
            field=models.CharField(blank=True, default="admin", max_length=255, null=True, verbose_name="更新人"),
        ),
        migrations.AlterField(
            model_name="executionlog",
            name="created_by",
            field=models.CharField(blank=True, default="admin", max_length=255, null=True, verbose_name="创建人"),
        ),
        migrations.AlterField(
            model_name="executionlog",
            name="deleted_by",
            field=models.CharField(blank=True, default="admin", max_length=255, null=True, verbose_name="删除人"),
        ),
        migrations.AlterField(
            model_name="executionlog",
            name="updated_by",
            field=models.CharField(blank=True, default="admin", max_length=255, null=True, verbose_name="更新人"),
        ),
        migrations.AlterField(
            model_name="intent",
            name="created_by",
            field=models.CharField(blank=True, default="admin", max_length=255, null=True, verbose_name="创建人"),
        ),
        migrations.AlterField(
            model_name="intent",
            name="deleted_by",
            field=models.CharField(blank=True, default="admin", max_length=255, null=True, verbose_name="删除人"),
        ),
        migrations.AlterField(
            model_name="intent",
            name="updated_by",
            field=models.CharField(blank=True, default="admin", max_length=255, null=True, verbose_name="更新人"),
        ),
        migrations.AlterField(
            model_name="task",
            name="created_by",
            field=models.CharField(blank=True, default="admin", max_length=255, null=True, verbose_name="创建人"),
        ),
        migrations.AlterField(
            model_name="task",
            name="deleted_by",
            field=models.CharField(blank=True, default="admin", max_length=255, null=True, verbose_name="删除人"),
        ),
        migrations.AlterField(
            model_name="task",
            name="updated_by",
            field=models.CharField(blank=True, default="admin", max_length=255, null=True, verbose_name="更新人"),
        ),
        migrations.AlterField(
            model_name="utterances",
            name="created_by",
            field=models.CharField(blank=True, default="admin", max_length=255, null=True, verbose_name="创建人"),
        ),
        migrations.AlterField(
            model_name="utterances",
            name="deleted_by",
            field=models.CharField(blank=True, default="admin", max_length=255, null=True, verbose_name="删除人"),
        ),
        migrations.AlterField(
            model_name="utterances",
            name="updated_by",
            field=models.CharField(blank=True, default="admin", max_length=255, null=True, verbose_name="更新人"),
        ),
    ]
