# Generated by Django 2.2.6 on 2021-11-09 15:07

import common.models.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("module_intent", "0019_auto_20211109_1122"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intent",
            name="developer",
            field=common.models.json.DictCharField(default="[]", verbose_name="开发商"),
        ),
    ]
