# Generated by Django 2.2.6 on 2021-12-22 16:16

import common.models.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_intent', '0021_auto_20211204_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionlog',
            name='params',
            field=common.models.json.DictCharField(default=[], verbose_name='执行参数'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intent',
            name='approver',
            field=common.models.json.DictCharField(default=[], verbose_name='审批人'),
        ),
    ]
