# Generated by Django 2.2.6 on 2021-12-22 16:22

import common.models.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_intent', '0022_auto_20211222_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionlog',
            name='params',
            field=common.models.json.DictCharField(default=[], verbose_name='执行参数'),
        ),
    ]
