# Generated by Django 2.2.6 on 2021-12-23 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_intent', '0023_auto_20211222_1622'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='executionlog',
            table='tab_execution_log',
        ),
    ]
