# Generated by Django 2.2.6 on 2021-12-23 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_intent', '0024_auto_20211223_1051'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bot',
            table='tab_bot',
        ),
        migrations.AlterModelTable(
            name='intent',
            table='tab_intent',
        ),
        migrations.AlterModelTable(
            name='task',
            table='tab_task',
        ),
        migrations.AlterModelTable(
            name='utterances',
            table='tab_utterances',
        ),
    ]
