# Generated by Django 2.2.6 on 2021-12-23 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_intent', '0025_auto_20211223_1054'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='executionlog',
            table='tab_intent_execution_log',
        ),
        migrations.AlterModelTable(
            name='task',
            table='tab_intent_task',
        ),
        migrations.AlterModelTable(
            name='utterances',
            table='tab_intent_utterances',
        ),
    ]
