# Generated by Django 2.2.16 on 2022-06-15 16:52

import common.models.base
import common.models.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeGroupModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='创建人')),
                ('created_at', common.models.base.FormatDateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='更新人')),
                ('updated_at', common.models.base.FormatDateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='删除人')),
                ('deleted_at', common.models.base.FormatDateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('biz_id', models.CharField(max_length=256, verbose_name='业务ID')),
                ('name', models.CharField(default='', max_length=256, verbose_name='名称')),
                ('trigger_id', models.IntegerField(verbose_name='触发器id')),
                ('trigger_name', models.CharField(max_length=256, verbose_name='触发器名称')),
                ('group_type', models.CharField(max_length=64, verbose_name='类型')),
                ('group_value', models.TextField(verbose_name='通知类型的值')),
            ],
            options={
                'verbose_name': '【通知群组】',
                'verbose_name_plural': '【通知群组】',
                'db_table': 'tab_notice_group',
            },
        ),
        migrations.CreateModel(
            name='TriggerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='创建人')),
                ('created_at', common.models.base.FormatDateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='更新人')),
                ('updated_at', common.models.base.FormatDateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='删除人')),
                ('deleted_at', common.models.base.FormatDateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('biz_id', models.CharField(default='system', max_length=256, verbose_name='业务ID')),
                ('name', models.CharField(default='', max_length=256, verbose_name='名称')),
                ('trigger_key', models.CharField(default='', max_length=64, unique=True, verbose_name='触发器key')),
                ('im_platform', models.CharField(default=0, max_length=256, verbose_name='平台')),
                ('im_type', models.CharField(default=0, max_length=256, verbose_name='im类型')),
                ('info', common.models.json.DictCharField(default='', verbose_name='触发器信息')),
            ],
            options={
                'verbose_name': '【触发器】',
                'verbose_name_plural': '【触发器】',
                'db_table': 'tab_trigger',
            },
        ),
        migrations.CreateModel(
            name='WhitelistModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='创建人')),
                ('created_at', common.models.base.FormatDateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='更新人')),
                ('updated_at', common.models.base.FormatDateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='删除人')),
                ('deleted_at', common.models.base.FormatDateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('biz_id', models.CharField(max_length=256, verbose_name='业务ID')),
                ('whitelist_ip', models.CharField(max_length=32, verbose_name='外网IP')),
            ],
            options={
                'verbose_name': '【业务白名单】',
                'verbose_name_plural': '【业务白名单】',
                'db_table': 'tab_whitelist',
            },
        ),
    ]
