# Generated by Django 2.2.16 on 2022-06-28 16:47

import common.models.base
import common.models.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticegroupmodel',
            name='group_value',
            field=common.models.json.DictCharField(verbose_name='通知类型的值'),
        ),
        migrations.CreateModel(
            name='AlarmStrategyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='创建人')),
                ('created_at', common.models.base.FormatDateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='更新人')),
                ('updated_at', common.models.base.FormatDateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='删除人')),
                ('deleted_at', common.models.base.FormatDateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('deal_alarm_name', models.CharField(max_length=256, verbose_name='处理套餐名称')),
                ('biz_id', models.CharField(max_length=256, verbose_name='业务ID')),
                ('alarm_source_type', models.IntegerField(choices=[(1, 'BKM'), (2, 'BCS')], verbose_name='告警源')),
                ('alarm_strategy', common.models.json.DictCharField(verbose_name='告警策略')),
                ('deal_strategy_type', models.IntegerField(choices=[(1, 'NOTICE'), (2, 'EVENT')], verbose_name='处理策略类型')),
                ('deal_strategy_value', common.models.json.DictCharField(verbose_name='处理策略值')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='是否启动')),
                ('config_id', models.CharField(max_length=256, verbose_name='处理套餐ID')),
            ],
            options={
                'verbose_name': '【告警策略】',
                'verbose_name_plural': '【告警策略】',
                'db_table': 'tab_alarm_strategy',
                'unique_together': {('biz_id', 'deal_alarm_name')},
            },
        ),
    ]
