# Generated by Django 2.2.16 on 2022-07-27 14:55

import common.models.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_notice', '0002_auto_20220628_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='triggermodel',
            name='im_type_id',
            field=models.CharField(default='', max_length=56, verbose_name='IM类型id'),
        ),
        migrations.AlterField(
            model_name='triggermodel',
            name='im_platform',
            field=models.CharField(max_length=256, verbose_name='平台'),
        ),
        migrations.AlterField(
            model_name='triggermodel',
            name='im_type',
            field=models.CharField(max_length=256, verbose_name='im类型'),
        ),
        migrations.AlterField(
            model_name='triggermodel',
            name='info',
            field=common.models.json.DictCharField(default=[], verbose_name='触发器信息'),
        ),
    ]
