# Generated by Django 2.2.16 on 2022-08-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_notice', '0004_auto_20220818_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmstrategymodel',
            name='translation_type',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='目标语言'),
        ),
    ]
