# Generated by Django 2.2.16 on 2022-09-01 13:10

import common.models.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_notice', '0008_auto_20220831_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskbroadcast',
            name='session_id',
        ),
        migrations.AddField(
            model_name='taskbroadcast',
            name='session_info',
            field=common.models.json.DictCharField(default={}, verbose_name='触发实时播报的信息'),
        ),
    ]
