# Generated by Django 2.2.16 on 2022-09-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_notice', '0009_auto_20220901_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskbroadcast',
            name='devops_build_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='蓝盾构建ID'),
        ),
        migrations.AddField(
            model_name='taskbroadcast',
            name='devops_pipeline_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='蓝盾流水线ID'),
        ),
        migrations.AddField(
            model_name='taskbroadcast',
            name='devops_project_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='蓝盾项目ID'),
        ),
    ]
