# Generated by Django 2.2.16 on 2022-09-20 19:04

import common.models.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_notice', '0010_auto_20220913_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskbroadcast',
            name='extra_notice_info',
            field=common.models.json.DictCharField(default=[], verbose_name='使用bkchat推送的额外人和群组'),
        ),
    ]
