# Generated by Django 2.2.16 on 2023-01-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_notice', '0011_taskbroadcast_extra_notice_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmstrategymodel',
            name='notify_interval',
            field=models.IntegerField(default=1, verbose_name='告警策略周期时间(min)'),
        ),
    ]
