# Generated by Django 2.2.16 on 2022-12-30 14:10

import common.models.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_notice', '0011_taskbroadcast_extra_notice_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskbroadcast',
            name='ladder_list',
            field=common.models.json.DictCharField(default=[5, 10, 20, 40, 60], verbose_name='播报的时间阶梯'),
        ),
    ]
