# Generated by Django 2.2.16 on 2023-11-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_notice', '0013_alarmstrategymodel_notify_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskbroadcast',
            name='retry_num',
            field=models.IntegerField(default=0, verbose_name='播报失败重试次数'),
        ),
    ]
