# Generated by Django 2.2.16 on 2024-06-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_notice', '0014_taskbroadcast_retry_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskbroadcast',
            name='custom_task_name',
            field=models.TextField(blank=True, null=True, verbose_name='自定义播报任务名'),
        ),
        migrations.AlterField(
            model_name='taskbroadcast',
            name='platform',
            field=models.CharField(choices=[('JOB', 'JOB'), ('SOPS', '标准运维'), ('DEVOPS', '蓝盾'), ('DEFINE', '自定义'), ('ITSM', 'ITSM')], max_length=32, verbose_name='任务所属平台'),
        ),
    ]
