# Generated by Django 2.2.6 on 2021-04-22 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("module_biz", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ChatGroupBusiness",
            new_name="ChatBindBusiness",
        ),
    ]
