# Generated by Django 2.2.6 on 2021-04-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module_biz", "0002_auto_20210422_1021"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatbindbusiness",
            name="chat_bot_type",
            field=models.CharField(
                choices=[
                    ("xwork", "企业微信"),
                    ("qq", "QQ"),
                    ("wechat", "微信"),
                    ("slack", "SLACK"),
                    ("default", "OPSBOT"),
                ],
                default="xwork",
                max_length=50,
                verbose_name="机器人类型",
            ),
        ),
    ]
