# Generated by Django 2.2.6 on 2021-04-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module_biz", "0003_auto_20210423_1209"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatbindbusiness",
            name="chat_index_id",
            field=models.CharField(default="-1", max_length=255, verbose_name="群聊ID索引"),
        ),
    ]
