# Generated by Django 2.2.16 on 2022-03-03 15:23

import common.models.base
import common.models.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='创建人')),
                ('created_at', common.models.base.FormatDateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='更新人')),
                ('updated_at', common.models.base.FormatDateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='删除人')),
                ('deleted_at', common.models.base.FormatDateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('domain_id', models.IntegerField(default=0, verbose_name='领域id')),
                ('intent_id', models.IntegerField(default=0, verbose_name='意图id')),
                ('data_source', models.CharField(default='', max_length=128, verbose_name='数据源')),
                ('text', models.TextField(blank=True, default='', null=True, verbose_name='文本数据')),
                ('slots', common.models.json.DictCharField(default='', verbose_name='词槽')),
            ],
            options={
                'db_table': 'tab_corpus',
            },
        ),
        migrations.CreateModel(
            name='CorpusDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='创建人')),
                ('created_at', common.models.base.FormatDateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='更新人')),
                ('updated_at', common.models.base.FormatDateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='删除人')),
                ('deleted_at', common.models.base.FormatDateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('domain_name', models.CharField(blank=True, max_length=128, unique=True, verbose_name='领域名称')),
                ('domain_key', models.CharField(blank=True, max_length=128, unique=True, verbose_name='领域key')),
            ],
            options={
                'db_table': 'tab_corpus_domain',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CorpusIntent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='创建人')),
                ('created_at', common.models.base.FormatDateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='更新人')),
                ('updated_at', common.models.base.FormatDateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='删除人')),
                ('deleted_at', common.models.base.FormatDateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('domain_id', models.IntegerField(default=0, verbose_name='领域id')),
                ('intent_key', models.CharField(blank=True, max_length=128, unique=True, verbose_name='意图key')),
                ('intent_name', models.CharField(blank=True, max_length=128, unique=True, verbose_name='意图名称')),
                ('slots', common.models.json.DictCharField(verbose_name='词槽')),
            ],
            options={
                'db_table': 'tab_corpus_intent',
            },
        ),
    ]
