# Generated by Django 2.2.6 on 2021-11-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module_nlp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="corpusdomain",
            name="domain_key",
            field=models.CharField(max_length=128, unique=True, verbose_name="领域key"),
        ),
        migrations.AlterField(
            model_name="corpusdomain",
            name="domain_name",
            field=models.CharField(max_length=128, unique=True, verbose_name="领域名称"),
        ),
    ]
