# Generated by Django 2.2.6 on 2021-11-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module_nlp", "0002_auto_20211102_1931"),
    ]

    operations = [
        migrations.RenameField(
            model_name="corpusintent",
            old_name="name",
            new_name="intent_name",
        ),
        migrations.AddField(
            model_name="corpusintent",
            name="intent_key",
            field=models.CharField(default="", max_length=128, verbose_name=""),
        ),
    ]
