# Generated by Django 2.2.6 on 2021-11-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module_nlp", "0003_auto_20211102_2014"),
    ]

    operations = [
        migrations.AlterField(
            model_name="corpusdomain",
            name="domain_key",
            field=models.CharField(blank=True, max_length=128, unique=True, verbose_name="领域key"),
        ),
        migrations.AlterField(
            model_name="corpusdomain",
            name="domain_name",
            field=models.CharField(blank=True, max_length=128, unique=True, verbose_name="领域名称"),
        ),
        migrations.AlterField(
            model_name="corpusintent",
            name="intent_key",
            field=models.CharField(blank=True, max_length=128, unique=True, verbose_name="意图key"),
        ),
        migrations.AlterField(
            model_name="corpusintent",
            name="intent_name",
            field=models.CharField(blank=True, max_length=128, unique=True, verbose_name="意图名称"),
        ),
    ]
