# Generated by Django 2.2.6 on 2021-11-05 15:51

import common.models.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("module_nlp", "0004_auto_20211105_1132"),
    ]

    operations = [
        migrations.AddField(
            model_name="corpusintent",
            name="slots",
            field=common.models.json.DictCharField(default={}, verbose_name="词槽"),
            preserve_default=False,
        ),
    ]
