# Generated by Django 2.2.6 on 2021-11-05 17:12

import common.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module_nlp", "0005_corpusintent_slots"),
    ]

    operations = [
        migrations.AddField(
            model_name="corpus",
            name="domain_id",
            field=models.IntegerField(default=0, verbose_name="领域id"),
        ),
        migrations.AlterField(
            model_name="corpus",
            name="updated_at",
            field=common.models.base.FormatDateTimeField(auto_now=True, null=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="corpusdomain",
            name="updated_at",
            field=common.models.base.FormatDateTimeField(auto_now=True, null=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="corpusintent",
            name="updated_at",
            field=common.models.base.FormatDateTimeField(auto_now=True, null=True, verbose_name="更新时间"),
        ),
    ]
