# Generated by Django 2.2.6 on 2021-11-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module_nlp", "0006_auto_20211105_1712"),
    ]

    operations = [
        migrations.AlterField(
            model_name="corpus",
            name="created_by",
            field=models.CharField(blank=True, default="admin", max_length=255, null=True, verbose_name="创建人"),
        ),
        migrations.AlterField(
            model_name="corpus",
            name="deleted_by",
            field=models.CharField(blank=True, default="admin", max_length=255, null=True, verbose_name="删除人"),
        ),
        migrations.AlterField(
            model_name="corpus",
            name="updated_by",
            field=models.CharField(blank=True, default="admin", max_length=255, null=True, verbose_name="更新人"),
        ),
        migrations.AlterField(
            model_name="corpusdomain",
            name="created_by",
            field=models.CharField(blank=True, default="admin", max_length=255, null=True, verbose_name="创建人"),
        ),
        migrations.AlterField(
            model_name="corpusdomain",
            name="deleted_by",
            field=models.CharField(blank=True, default="admin", max_length=255, null=True, verbose_name="删除人"),
        ),
        migrations.AlterField(
            model_name="corpusdomain",
            name="updated_by",
            field=models.CharField(blank=True, default="admin", max_length=255, null=True, verbose_name="更新人"),
        ),
        migrations.AlterField(
            model_name="corpusintent",
            name="created_by",
            field=models.CharField(blank=True, default="admin", max_length=255, null=True, verbose_name="创建人"),
        ),
        migrations.AlterField(
            model_name="corpusintent",
            name="deleted_by",
            field=models.CharField(blank=True, default="admin", max_length=255, null=True, verbose_name="删除人"),
        ),
        migrations.AlterField(
            model_name="corpusintent",
            name="updated_by",
            field=models.CharField(blank=True, default="admin", max_length=255, null=True, verbose_name="更新人"),
        ),
    ]
