# Generated by Django 2.2.6 on 2021-11-09 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("module_nlp", "0007_auto_20211109_1100"),
    ]

    operations = [
        migrations.RenameField(
            model_name="corpus",
            old_name="slot",
            new_name="slots",
        ),
    ]
