# Generated by Django 2.2.6 on 2021-12-01 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("module_nlp", "0008_auto_20211109_1155"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="corpusdomain",
            options={"ordering": ["-id"]},
        ),
    ]
