# Generated by Django 2.2.6 on 2021-04-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatGroupBusiness",
            fields=[
                (
                    "created_by",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="创建人"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="更新人"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="更新时间"),
                ),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                (
                    "deleted_by",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="删除人"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "chat_group_id",
                    models.CharField(
                        default="-1",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="群聊ID",
                    ),
                ),
                (
                    "chat_bot_type",
                    models.CharField(
                        choices=[
                            ("WEWORK", "企业微信"),
                            ("QQ", "QQ"),
                            ("WX", "微信"),
                            ("SLACK", "SLACK"),
                        ],
                        default="WEWORK",
                        max_length=50,
                        verbose_name="机器人类型",
                    ),
                ),
                ("biz_id", models.PositiveIntegerField(default=0, verbose_name="业务ID")),
                (
                    "biz_name",
                    models.CharField(default="", max_length=255, verbose_name="业务名称"),
                ),
            ],
            options={
                "verbose_name": "群ID绑定业务表",
                "verbose_name_plural": "群ID绑定业务表",
            },
        ),
    ]
