# Generated by Django 2.2.16 on 2022-05-27 11:09

import common.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_biz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BizVariableModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='创建人')),
                ('created_at', common.models.base.FormatDateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='更新人')),
                ('updated_at', common.models.base.FormatDateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='删除人')),
                ('deleted_at', common.models.base.FormatDateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('key', models.CharField(default='', max_length=128, verbose_name='全局变量的key')),
                ('name', models.CharField(default='', max_length=128, verbose_name='全局变量name')),
                ('biz_id', models.CharField(default='', max_length=128, verbose_name='业务ID')),
                ('value', models.TextField(default='', verbose_name='变量值')),
                ('type', models.CharField(default='', max_length=128, verbose_name='类型')),
                ('ase_key', models.CharField(default='', max_length=128, verbose_name='ase_key')),
            ],
            options={
                'verbose_name': '业务变量',
                'verbose_name_plural': '业务变量',
                'db_table': 'tab_biz_variable',
                'unique_together': {('key', 'biz_id')},
            },
        ),
    ]
