# Generated by Django 2.2.6 on 2021-05-12 17:15
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('module_biz', '0004_chatbindbusiness_chat_index_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbindbusiness',
            name='chat_group_name',
            field=models.CharField(
                default='-', max_length=255, verbose_name='群聊名称'),
        ),
    ]
