# Generated by Django 2.2.6 on 2021-07-05 20:46

from django.db import migrations
import common.models.base


class Migration(migrations.Migration):

    dependencies = [
        ("module_biz", "0005_chatbindbusiness_chat_group_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatbindbusiness",
            name="created_at",
            field=common.models.base.FormatDateTimeField(auto_now_add=True, null=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="chatbindbusiness",
            name="deleted_at",
            field=common.models.base.FormatDateTimeField(blank=True, null=True, verbose_name="删除时间"),
        ),
        migrations.AlterField(
            model_name="chatbindbusiness",
            name="updated_at",
            field=common.models.base.FormatDateTimeField(blank=True, null=True, verbose_name="更新时间"),
        ),
    ]
