# Generated by Django 2.2.6 on 2021-11-05 17:12

import common.models.base
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("module_biz", "0006_auto_20210705_2046"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatbindbusiness",
            name="updated_at",
            field=common.models.base.FormatDateTimeField(auto_now=True, null=True, verbose_name="更新时间"),
        ),
    ]
