# Generated by Django 2.2.6 on 2021-12-23 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_biz', '0008_auto_20211204_1706'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chatbindbusiness',
            table='tab_chat_bind_business',
        ),
    ]
