# Generated by Django 2.2.16 on 2022-03-03 15:23

import common.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='创建人')),
                ('created_at', common.models.base.FormatDateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='更新人')),
                ('updated_at', common.models.base.FormatDateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='删除人')),
                ('deleted_at', common.models.base.FormatDateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('biz_id', models.PositiveIntegerField(default=0, verbose_name='业务ID')),
                ('biz_name', models.CharField(default='', max_length=128, verbose_name='业务名称')),
                ('faq_name', models.CharField(default='', max_length=128, verbose_name='知识库名称')),
                ('faq_db', models.CharField(default='', max_length=128, verbose_name='知识库DB')),
                ('faq_collection', models.CharField(default='', max_length=128, verbose_name='知识库表名')),
                ('num', models.CharField(default='', max_length=128, verbose_name='QA数量')),
                ('member', models.TextField(default='', verbose_name='维护人员')),
            ],
            options={
                'verbose_name': '【知识库】',
                'verbose_name_plural': '【知识库】',
                'db_table': 'tab_faq',
            },
        ),
    ]
