# Generated by Django 2.2.6 on 2021-04-23 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("module_faq", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="faq",
            old_name="create_by",
            new_name="created_by",
        ),
        migrations.RenameField(
            model_name="faq",
            old_name="is_delete",
            new_name="is_deleted",
        ),
        migrations.RenameField(
            model_name="faq",
            old_name="update_time",
            new_name="updated_time",
        ),
    ]
