# Generated by Django 2.2.6 on 2021-04-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module_faq", "0002_auto_20210423_1048"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faq",
            name="updated_time",
        ),
        migrations.AddField(
            model_name="faq",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="创建时间"
            ),
        ),
        migrations.AddField(
            model_name="faq",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
        ),
        migrations.AddField(
            model_name="faq",
            name="deleted_by",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="删除人"
            ),
        ),
        migrations.AddField(
            model_name="faq",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="描述"),
        ),
        migrations.AddField(
            model_name="faq",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="更新时间"),
        ),
        migrations.AddField(
            model_name="faq",
            name="updated_by",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="更新人"
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="created_by",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="创建人"
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="是否删除"),
        ),
    ]
