# Generated by Django 2.2.6 on 2021-12-23 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_faq', '0006_auto_20211204_1706'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='faq',
            table='tab_faq',
        ),
    ]
