# Generated by Django 2.2.16 on 2022-03-11 15:36

import common.models.base
import common.models.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VersionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='创建人')),
                ('created_at', common.models.base.FormatDateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='更新人')),
                ('updated_at', common.models.base.FormatDateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='删除人')),
                ('deleted_at', common.models.base.FormatDateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_show', models.BooleanField(verbose_name='是否展示')),
                ('version', models.CharField(max_length=255, unique=True, verbose_name='版本')),
                ('title', models.CharField(max_length=255, verbose_name='主题')),
                ('context', common.models.json.DictCharField(verbose_name='内容')),
                ('author', models.CharField(max_length=128, verbose_name='发版人')),
            ],
            options={
                'db_table': 'tab_version',
            },
        ),
    ]
