# Generated by Django 2.2.16 on 2022-03-18 15:44

import common.models.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_other', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='versionmodel',
            options={'verbose_name': '【版本】', 'verbose_name_plural': '【版本】'},
        ),
        migrations.AlterField(
            model_name='versionmodel',
            name='context',
            field=common.models.json.DictCharField(help_text='输入一个字符串数组', verbose_name='内容'),
        ),
    ]
