# Generated by Django 2.2.16 on 2022-05-18 11:34

import common.models.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_other', '0005_imtypemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='imtypemodel',
            name='alias',
            field=models.CharField(default='', max_length=256, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imtypemodel',
            name='define',
            field=common.models.json.DictCharField(default={}),
        ),
    ]
