# Generated by Django 2.2.16 on 2022-05-18 14:20

import common.models.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_other', '0006_auto_20220518_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imtypemodel',
            name='alias',
            field=models.CharField(max_length=256, verbose_name='别名'),
        ),
        migrations.AlterField(
            model_name='imtypemodel',
            name='define',
            field=common.models.json.DictCharField(default=[]),
        ),
    ]
