# Generated by Django 2.2.16 on 2022-07-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_other', '0007_auto_20220518_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='imtypemodel',
            name='im_type_id',
            field=models.CharField(default='', max_length=56, verbose_name='im类型id'),
            preserve_default=False,
        ),
    ]
