# Generated by Django 2.2.16 on 2022-09-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_other', '0009_auto_20220818_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqmodel',
            name='remote_url',
            field=models.URLField(default='', verbose_name='远程知识库的数据url'),
        ),
    ]
