# Generated by Django 2.2.16 on 2023-08-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_other', '0010_faqmodel_remote_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='versionmodel',
            name='context_type',
            field=models.CharField(choices=[('text', 'text'), ('markdown', 'markdown')], default='text', max_length=32, verbose_name='内容类型'),
        ),
    ]
