# Generated by Django 2.2.16 on 2022-05-06 20:36

import common.models.base
import common.models.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TriggerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='创建人')),
                ('created_at', common.models.base.FormatDateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='更新人')),
                ('updated_at', common.models.base.FormatDateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='删除人')),
                ('deleted_at', common.models.base.FormatDateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('name', models.CharField(default='', max_length=256, verbose_name='名称')),
                ('platform', models.CharField(default=0, max_length=256, verbose_name='平台')),
                ('trigger_type', models.CharField(default=0, max_length=256, verbose_name='触发器类型')),
                ('trigger_key', models.CharField(default='', max_length=256, verbose_name='触发器key')),
                ('info', common.models.json.DictCharField(default='', verbose_name='触发器信息')),
            ],
            options={
                'db_table': 'tab_trigger',
            },
        ),
    ]
