# Generated by Django 2.2.16 on 2022-05-26 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_trigger', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='triggermodel',
            options={'verbose_name': '【触发器】', 'verbose_name_plural': '【触发器】'},
        ),
    ]
