# Generated by Django 2.2.6 on 2021-12-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_timer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timermodel',
            name='timer_user',
            field=models.CharField(default='', max_length=128, verbose_name='定时任务添加人'),
        ),
    ]
