# Generated by Django 2.2.6 on 2021-12-04 17:06

import common.models.base
import common.models.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='创建人')),
                ('created_at', common.models.base.FormatDateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='更新人')),
                ('updated_at', common.models.base.FormatDateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='删除人')),
                ('deleted_at', common.models.base.FormatDateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('plugin_key', models.CharField(max_length=128, unique=True, verbose_name='插件key')),
                ('plugin_icon', models.CharField(max_length=512, verbose_name='插件图标')),
                ('plugin_name', models.CharField(max_length=128, unique=True, verbose_name='插件名称')),
                ('plugin_addr', models.CharField(max_length=256, verbose_name='插件地址')),
                ('plugin_desc', models.CharField(max_length=512, verbose_name='插件描叙')),
                ('plugin_tag', models.CharField(max_length=128, verbose_name='插件标签')),
                ('plugin_status', models.IntegerField(choices=[(0, 'DEFAULT'), (1, 'STAG'), (2, 'AUDIT'), (3, 'ADDED'), (4, 'SOLD_OUT')], default=0, verbose_name='插件状态')),
                ('plugin_type', models.IntegerField(choices=[(0, 'PRIVATE'), (1, 'PUBLIC')], default=0, verbose_name='插件类型')),
                ('biz_list', common.models.json.DictCharField(default=[], verbose_name='生效业务')),
                ('developers', common.models.json.DictCharField(default=[], verbose_name='开发者')),
                ('actions', common.models.json.DictCharField(default=[], verbose_name='插件动作')),
                ('plugin_global', common.models.json.DictCharField(default={}, verbose_name='全局变量')),
            ],
            options={
                'db_table': 'tab_plugins',
            },
        ),
    ]
