# Generated by Django 2.2.16 on 2022-03-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_plugin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='plugin_start',
            field=models.CharField(default='', max_length=128, verbose_name='开始action'),
        ),
        migrations.AddField(
            model_name='plugin',
            name='plugin_web',
            field=models.CharField(default='', max_length=128, verbose_name='web使用action'),
        ),
    ]
