# Generated by Django 2.2.6 on 2021-12-07 09:34

import common.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_plugin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginAuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='创建人')),
                ('created_at', common.models.base.FormatDateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='更新人')),
                ('updated_at', common.models.base.FormatDateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_by', models.CharField(blank=True, default='admin', max_length=255, null=True, verbose_name='删除人')),
                ('deleted_at', common.models.base.FormatDateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('sn', models.CharField(max_length=255, unique=True, verbose_name='单据号')),
                ('sn_status', models.IntegerField(choices=[(0, 'DEFAULT'), (1, 'PASS'), (2, 'NO_PASS')], default=0, verbose_name='单据审核状态')),
                ('plugin_id', models.IntegerField(verbose_name='插件单据')),
            ],
            options={
                'db_table': 'tab_plugin_audit_log',
            },
        ),
    ]
