# Generated by Django 2.2.16 on 2022-03-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_plugin', '0002_auto_20220304_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='plugin_wait_time',
            field=models.IntegerField(default=0, verbose_name='等待时间'),
        ),
    ]
