# Generated by Django 2.2.6 on 2021-12-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_plugin', '0002_pluginauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginauditlog',
            name='plugin_username',
            field=models.CharField(default=1, max_length=255, verbose_name='添加人'),
            preserve_default=False,
        ),
    ]
