# Generated by Django 2.2.6 on 2021-12-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_plugin', '0003_pluginauditlog_plugin_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='plugin_exec_count',
            field=models.IntegerField(default=0, verbose_name='执行总次数'),
        ),
        migrations.AddField(
            model_name='plugin',
            name='plugin_lately_count',
            field=models.IntegerField(default=0, verbose_name='插件最近执行次数'),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='plugin_status',
            field=models.IntegerField(choices=[(0, 'DEFAULT'), (1, 'AUDIT'), (2, 'ADDED'), (3, 'SOLD_OUT')], default=0, verbose_name='插件状态'),
        ),
    ]
