# Generated by Django 2.2.6 on 2021-12-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_plugin', '0004_auto_20211208_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='choose_biz',
            field=models.BooleanField(default=False, verbose_name='选择业务'),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='plugin_lately_count',
            field=models.IntegerField(default=0, verbose_name='插件最近30天执行次数'),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='plugin_status',
            field=models.IntegerField(choices=[(0, 'DEFAULT'), (1, 'STAG'), (2, 'AUDIT'), (3, 'ADDED'), (4, 'SOLD_OUT')], default=0, verbose_name='插件状态'),
        ),
    ]
