# Generated by Django 2.2.6 on 2021-12-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module_plugin", "0005_auto_20211210_1707"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plugin",
            name="plugin_status",
            field=models.IntegerField(
                choices=[(0, "DEFAULT"), (1, "STAG"), (2, "AUDIT"), (3, "ADDED"), (4, "SOLD_OUT"), (5, "CANCEL_AUDIT")],
                default=0,
                verbose_name="插件状态",
            ),
        ),
    ]
